version: '2'
services:
  wor: 
    image: worker
    build: ../worker/
    links:
     - bro
    environment:
     - BROKER_URL=tcp://bro:8001
  cli:
    image: client
    build: ../client/
    links:
     - bro
    environment:
     - BROKER_URL=tcp://bro:8000
  bro:
    image: broker
    build: ../broker/
