version: '3'

services:
  nodejs:
    build:
      context: ./misitio_nodejs
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='student'
      - MYSQL_DATABASE='robotnikdb'
      - MYSQL_HOST=db
    ports:
      - "8000:8080"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - .:/home/node/app
      - ./misitio_nodejs/nodejs-microservice/serverROS:/usr/src/serverROS/
    networks:
      - app-network
    command: ./wait-for.sh db:3306 -- /usr/src/serverROS/node_modules/.bin/nodemon server.js 

  db:
    build:
      context: ./misitio_db
      dockerfile: Dockerfile
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=student 
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:     
      - dbdata:/var/lib/mysql/
    networks:
       - app-network  

networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
